### PR TITLE
Add TTL support

### PR DESCRIPTION
**Pull request by obeattie**
Reference #26.

### CODE REVIEW

**Comment by crufter** [comment]
@obeattie, I wonder how important it is to set the TTL on a per row basis? If let's say in 95% of the use cases TTL is a per table property I would prefer to not introduce the SetWithTTL, but rather a group of TTL related methods which could be an embedded interface 'TTLer' or something similar.

Apart from that this looks pretty good.

**Comment by obeattie** [comment]
I'm not sure I'd agree that 95% of use-cases have a table-wide TTL (from my experience), though others' mileage may vary. Would be interested in your opinions, @jcampan, @chrusty…

If this per-row functionality can't exist though, it immediately rules out both use-cases for this library I have in mind.

**Comment by crufter** [comment]
The was a question, not a statement :).

> _If_ let's say

If you have a use case in mind already, then I am sold.

**Comment by obeattie** [comment]
I do want to implement per-column TTLs before this is merged, though (again, I have a use-case for this).

**Comment by andreas** [comment]
Would it work with a signature like this `Set(v interface{}, options ...Option)`?

**Comment by crufter** [comment]
How about this: we introduce a WriteOptions interface?

**Comment by obeattie** [comment]
@andreas I did consider having an `Options` struct too. Not sure I'm sold on it though. What other options do we want to be able to set?

**Comment by crufter** [comment]
Haha, @andreas nice timing. So yeah, I went the Options route in previous iterations in this library.
@obeattie The fact that the moment you have an other option in the future the current 'framework' breaks is jarring to me.

By breaking I mean:
We have SetWithTTL now, and if we have to introduce SetWithSomethingElse, what if you need both? SetWithTTLAndSomethingElse? A WriteOptions struct would be a more future proof design.

**Comment by chrusty** [comment]
I think that these are the TTL options:
- Per-table (set in the schema and automatically applied to EVERYTHING that gets written to the table)
- Per-column (an optional extra on every write query which over-rides the table default)

We should DEFINITELY support having per-table AND per-column options here, obviously useful for times when we might want to override the table-wide default (for example we may want to have a table with no default TTL, then choose to TTL certain values).

**Comment by obeattie** [comment]
Okay; I will implement this with a `WriteOptions` struct. I agree it's a good idea. How we do per-column options needs to be considered (rather than per-row). It can probably be specified in the struct somehow.

**Comment by jcampan** [comment]
Have the possibility to set a TTL per query is very useful. Sometimes you need to keep some data forever, some for few days, in the same table. (JobPoints for exemple.)

After for the TTL per column :
 In Cassandra you can set different TTL for different column, but you cannot set them in only one query.
That mean that we will need to split the query and perform several write instead of one.

Last point : we should be able to use the update function with TTL.

One question, why the TTL is not an optional parameter of the Set and Update function ?

**Comment by andreas** [comment]
To clarify, this is what I had in mind with the variadic options argument: http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by crufter** [comment]
@jcampan Generally optional parameters are not considered idiomatic in Go. That does not mean we can not use the ...syntax to emulate optional params if we all agree here.

**Comment by crufter** [comment]
@andreas Can you post the example you sent me? I feel your approach is different than what @obeattie and I have in mind.

**Comment by andreas** [comment]
To clarify even further :wink: I didn't mean we need to use functions specifically, just the variadic part:

`Set(x, nil)` vs `Set(x)`
and
`Set(x, gocassa.Options{TTL: 10 * time.Minute})` vs `Set(x, gocassa.TTL(10 * time.Minute))`

**Comment by obeattie** [comment]
``` go
Set(x)
```

(as it is now; using purely default options)

``` go
SetWithOptions(x, gocassa.Options{
    TTL: 2 * time.Minute,
})
```

(allows specification of options, using a struct)

Abusing variadic arguments feels like heavy cruft: there's no type safety, you'd have to remember the order the arguments are supposed to be in, there would undoubtedly be cases where the meaning of a supplied argument is ambiguous. **Note I am not criticising the approach @andreas has proposed here. That looks good also.**

I'm ambivalent as to whether we just have a single `Set` method that mandates specification of options, or a combination of a regular no-options `Set` and also `SetWithOptions`.

**Comment by crufter** [comment]
@obeattie, in @andreas's proposal the order of (option) arguments do not matter.

I vote for having struct as you do now, @obeattie and having a separate Set and SetWithOptions (although I don't have strong preferences in this matter, apart from moving from TTL to a generalized Options).

**Comment by andreas** [comment]
> there's no type safety

Could the option type be non-exported and then exported functions return values of this type? That could ensure type safety. Otherwise it would just be up to correct use, which is not too bad considering the level of type safety in Go anyway.

> you'd have to remember the order the arguments are supposed to be in

I think the order of the variadic arguments should not matter: `Set(x, gocassa.TTL(1 * time.Minute), gocassa.CLOne))` should be the same as `Set(x, gocassa.TTL(1 * time.Minute), gocassa.CLOne))`.

> there would undoubtedly be cases where the meaning of a supplied argument is ambiguous

It's true you would be able to pass in silly arguments, e.g. `Set(x, gocassa.TTL(1 * time.Minute),  gocassa.TTL(2 * time.Minute))`, but if we just evaluate options in order left-to-right, then it should be fairly straight forward to understand.

**Comment by obeattie** [comment]
@crufter @andreas When I referred to "variadic arguments" I was responding to the discussion above your proposal. However, I still think I prefer the struct approach myself.

**Comment by crufter** [comment]
@obeattie Works for me as well.

**Comment by obeattie** [comment]
I've added support for the `Options` stuff discussed above. Per-column TTLs look to be [a tad more cumbersome](http://grokbase.com/t/cassandra/user/136kd5p7p2/ttl-cant-be-speciefied-at-column-level-using-cql-3-in-cassandra-1-2-x) to add than I'd hoped. It's still possible to do, but not sure worthwhile right now.

**Comment by crufter** [comment]
@obeattie Let's merge per row TTLs (when ready) and then do per table, per column later?

**Comment by obeattie** [comment]
@crufter :+1:, so long as we are happy with the interface(s) for this functionality.

**Comment by obeattie** [comment]
I have an implementation of per-table `Options` defaults in my local repo already. I'll wait until this PR is merged then submit that.

**Comment by crufter** [comment]
@obeattie

```
./filter.go:37: undefined: strconv
```

**Comment by crufter** [comment]
There is a failing test, which passes in master:

```
=== RUN TestTimeSeriesT
--- FAIL: TestTimeSeriesT (0.16 seconds)
    timeseries_table_test.go:29: Missing mandatory PRIMARY KEY part bucket
```

**Comment by crufter** [comment]
LGTM :+1:

**Pull request merged**
