### PR TITLE
Nullable fields

### PR DESCRIPTION
**Pull request by thoas**
You will find in this PR:
- A refactor of the StructInfo mechanism
- Removing of panic in table initialization (it can be removed if you don't want it)

I have added some tests in the reflect library but will provide some real cases in the next few hours.

Feedback welcome :)

### CODE REVIEW

**Comment by crufter** [comment]
Very nice!

Extra thanks for the documentation and examples.

My only concern is the removal of panics from table initialisation: the change is not backward compatible, and the go convention allows for panics when a programmer supplies a wrong type to a method: http://www.reddit.com/r/golang/comments/2a1sie/when_to_call_panic/

Can you remove it for the time being? It is not related to the feature in question anyway, let's get back to it after the merge of the nullable fields feature.

**Comment by thoas** [comment]
No problem about it, I will remove this stuff.

**Comment by crufter** [comment]
Cheers!

An other think: it might be just me, but this could be more aptly named non nullable fields?
At the moment every field is nullable.

**Comment by thoas** [comment]
We are back to panic now!

Interesting question, I have called them nullable because of non zero values and instead of having horrible default values, you will just have `null`.

I'm probably wrong about the term, you can propose a better one :)

Tests are not passing on travis, investigating.

**Comment by crufter** [comment]
@thoas 

It was just a problem with travis, I restarted the build and it's all good know.
Let me think about the naming, meanwhile I will read the code.

Thank you again.

**Comment by crufter** [comment]
@thoas Createtable does not work when using the null struct tag, ;null ends up in the create statement like this:

```
fieldname;null varchar,
```

Edit:

Create table does not respect struct tags at all (obviously this problem existed already in the codebase).
I think I will merge this though, because that is definitely not a problem with this PR.

I think we should name this 'omitempty', like how the json does it: http://golang.org/pkg/encoding/json/

```
Field int `json:"myName,omitempty"`
```

**Comment by thoas** [comment]
hi @crufter,

Sorry for the delay, thank you for your time in this PR I will close it since I will not use gocassa for my project.

I'm currently implementing a cassandra dialect in [gorm](https://github.com/jinzhu/gorm/compare/master...thoas:master) to reuse its API (preloading, etc.).

Also, I will keep this bunch of code in my personal gocassa repository if you are willing to reuse it :)

**Comment by crufter** [comment]
@thoas Cheers I think I will pick up this PR and merge this if you don't mind. I like the feature idea a lot.

**Comment by thoas** [comment]
no problem @crufter don't hesitate to ping me when you will do that

And thank you again for your time

**Pull request closed without merging**
