### PR TITLE
Clean up WHERE clause generation

### PR DESCRIPTION
**Pull request by obeattie**
- Clean up `WHERE` statement construction
- Don't output a `WHERE` clause if there are no actual predicates within it
- Add a `Name()` method to `Table`, returning its underlying name as stored in C*

### CODE REVIEW

**Comment by jcampan** [comment]
Allow users to perform SELECTs from all table types (with Where()) is going against recipe concept.

**Comment by obeattie** [comment]
I put this in HipChat, but to keep the discussion on GitHub:

I agree that we shouldn't necessarily encourage users to build their own queries, and we should make it as easy as possible for them to "do the recommended thing," but in the case that they actually know what they are doing, I don't think we should explicitly prevent them. Right now, I don't even know the name of a table that Gocassa creates, so I can't even issue a query like this myself.

Separately, I consider the emission of a statement like `SELECT foo FROM bar WHERE` (ie. one without predicates) a bug: that's just invalid CQL. That should be fixed regardless.

**Comment by crufter** [comment]
- What if we don't include this in the interface but people have to type assert down to an exact recipe type and let this access from there? (Same could be done for TableChanger?)
- What if we just return the Table type for people who need it - I feel like `Select` won't cut it for some people and we end up including the whole Table in all recipes.

**Comment by obeattie** [comment]
@crufter I was thinking about just going the type assertion route myself. Another option would be to have a `Table()` method in the recipe interfaces that return the underlying `Table` object.

**Comment by obeattie** [comment]
I've removed the `Selectable` stuff. I agree that type assertions work better. I still think that `WHERE` needs to be fixed regardless (so I've updated the PR to reflect this).

**Pull request merged**
