### PR TITLE
Swapping panics for errors

### PR DESCRIPTION
**Pull request by domwong**
We probably don't want to be panicking in the library. We should convert to errors

### CODE REVIEW

**Comment by crufter** [comment]
This is assuming we are trying to follow Go conventions (and we don't have an 'inside Hailo' way of doing things):

Panics are usually acceptable if they are due to a programmer error (if they are due to gross misuse of a library). At least that was the accepted opinion last time I checked.

I will see what is the convention in Go land now and go over the ones you swapped and see if any of them do not fit the accepted pattern.

I would prefer the gofmt in a separate PR since that is a nobrainer (and makes it easier to see what was a nonformat change).

**Comment by domwong** [comment]
Fair point. It's somewhat hazy but my preference would be to not crash the service. FWIW https://golang.org/doc/effective_go.html#panic

**Comment by crufter** [comment]
Services should be resistant to panics anyway (handler should catch it). There is no error return for division by zero for example: 42/0. Neither for nil pointers. Both are similar errors to passing wrong type.

**Comment by crufter** [comment]
I am somewhat ashamed to reference reddit but (will find something more official later): http://www.reddit.com/r/golang/comments/2a1sie/when_to_call_panic/

```
Panics should be used in two cases:
An unrecoverable error where your program cannot guarantee the state (thus being unrecoverable)
Or a programmer error (e.g. passing a wrong type)
```

As I said I will go through your PR and see which panic -> error conversion do not fit the above cases, and I will merge those.

**Comment by domwong** [comment]
The handlers are resistant to panic, yes. If someone does this outside of a handler then it won't recover. Anyway, I'm not wedded to it. Closing.

**Pull request closed without merging**
