### PR TITLE
Update gocassa reflect import path

### PR DESCRIPTION
**Pull request by h7kanna**

### CODE REVIEW

**Comment by dancannon** [comment]
Thanks for the contribution @h7kanna, sorry for not catching this sooner! It looks like there are some imports in the examples that need to be corrected and a couple of links in the README, would you be able to have a look at those?

**Comment by h7kanna** [comment]
Sure. Will update those too. Thank you.

**Comment by h7kanna** [comment]
Hi @dancannon , updated remaining references other than travis related paths in README. Thank you.

**Comment by crufter** [comment]
LGTM

**Comment by dancannon** [comment]
Thanks @h7kanna! 👍

**Pull request merged**
